### ISSUE TITLE
Version Conflict of Boost and zlib

### ISSUE THREAD

**Issue by priyadhiman007** [szczurek-lab/DataFilter#2]
Hello, 

I am facing the version conflict issue "_version conflict boost 1.79 ->zlib 1.2.13, None->zlib 1.2.12_" while running the Data Filters. I am using recommended library versions but there is an error after running the **conan** command: _conan install .. -s build_type=Release_.  I have updated the PATH variable and have tried using different versions of zlib but nothing seems to be working. 

Can you please tell me what could be the problem? Any help would be highly appreciated.

Thank you.

**Comment by senbaikang** [comment]
Hello,

Sorry for the late reply. Have you also tried to lower down the version of boost to, for example, 1.70?

**Comment by priyadhiman007** [comment]
Hi,
Thank you for replying. I was able to resolve it for Boost but now it is showing version conflict w.r.t. zlib. I have zlib verison 1.2.13 but still it is not working.
Do you have Docker container created already with all the requirements satisfied which I can use directly?
Any help is appreciated!
Thank you!

**Comment by senbaikang** [comment]
Hi,

As a quick fix, I have updated the [docker file in the SIEVE repo](https://github.com/szczurek-lab/SIEVE/commit/ec63be79d1b67f228b3256c0a785ed2946cc499c), where DataFilter is included. Please build it, have a test, and let me know if it works.

Best,
Senbai

**Comment by priyadhiman007** [comment]
I am so thankful for this fix! 
One quick question though, what do I need to give as input for data in the Snakefile now? 
The data it is expecting as input is supposed to be the output of the read count matrix that I'll be passing in the DataFilter repo right?
So do I need to pass the read count matrix only here ?

**Comment by senbaikang** [comment]
yes you are right. You have to first run DataFilter within the container to get the output, and then give it to the pipeline to run SIEVE.

**Comment by priyadhiman007** [comment]
Thank you so much for the help!
