### ISSUE TITLE
Running into Floating point exception error

### ISSUE THREAD

**Issue by priyadhiman007** [szczurek-lab/DataFilter#3]
Hi, 
I am trying to run Datafilters on the following files with 2000 cells, but I'm running into the error:
"Reading cell names... Done.
0 files processed.
Floating point exception (core dumped)"

Cell name file: https://drive.google.com/file/d/11sQ-_peII5Gn2Yq94cMnMHZDlk84rC5Y/view?usp=sharing
Mpileup file: https://drive.google.com/file/d/11XYgAq2w1Gr-QeEsw6Msr63cj7OLBYc_/view?usp=sharing

Could you help me identify what might be causing this?

Thank you!

**Comment by senbaikang** [comment]
Though this is huge, I am able to run it.

Command that I used:
`datafilter --cellNames cell2000.txt --in sc_2000_50output.mpileup -o output.tsv`

**Comment by priyadhiman007** [comment]
Thank you Senbai!
I am able to run it now.
